12 - Python Recap of lists and numpy arrays

1.   python自動判斷變數型態
2.   tuple1不可變
3.   index從0開始
4.   numpy more sample
5.   lib= 不必重發明輪子



In [3]:
# 觀察變數型態
a = 3
b = 5.
c = 'chan'
d = [1,2,3,4,5]

In [4]:
d = [1, 'chan', 5.]

In [5]:
e = (1,2,3,4,5)

In [7]:
f = e[3]
f

4

In [9]:
e = (1, 'chan', 5.)
e[2]

5.0

In [12]:
print(d*2)
b = [i*2 for i in d]
print(b)

[1, 'chan', 5.0, 1, 'chan', 5.0]
[2, 'chanchan', 10.0]


In [16]:
import numpy as np

a = np.array([2,4,6,8])
print(a*2)
print(a**2)

[ 4  8 12 16]
[ 4 16 36 64]


In [18]:
from cv2 import imread, imwrite
# for google colab
from google.colab import drive
import os
drive.mount('/content/gdrive')
path = r"/content/gdrive/My Drive/screeni_practice"
os.chdir( path )
retval = os.getcwd()
print("目錄修改成功:%s" % retval)

Mounted at /content/gdrive
目錄修改成功:/content/gdrive/My Drive/screeni_practice


In [21]:
img = imread('images/test_image.jpg')
print(img)

[[[ 51  29   1]
  [ 50  28   0]
  [ 50  28   0]
  ...
  [141  96  45]
  [141  96  45]
  [141  96  45]]

 [[ 51  29   1]
  [ 51  29   1]
  [ 51  29   1]
  ...
  [140  95  44]
  [140  95  44]
  [140  95  44]]

 [[ 52  31   0]
  [ 52  31   0]
  [ 51  29   1]
  ...
  [138  95  44]
  [138  95  44]
  [138  95  44]]

 ...

 [[106  81  71]
  [106  81  71]
  [106  80  73]
  ...
  [190 152 120]
  [190 152 120]
  [190 152 120]]

 [[104  79  69]
  [104  79  69]
  [104  78  71]
  ...
  [186 148 116]
  [186 148 116]
  [186 148 116]]

 [[102  77  67]
  [102  77  67]
  [102  76  69]
  ...
  [188 150 118]
  [188 150 118]
  [188 150 118]]]


In [23]:
img_tinted = img * [1, 0, 0]
imwrite('images/tinted2.jpg', img_tinted)

True